const scaleTypes = {
  ADD_NOTE: 'ADD_NOTE',
  LOAD_SCALE: 'LOAD_SCALE',
  REMOVE_NOTE: 'REMOVE_NOTE',
  SCALE_DELETE_ERROR: 'SCALE_DELETE_ERROR',
  SCALE_DELETE_SUCCESSFUL: 'SCALE_DELETE_SUCCESSFUL',
  SCALE_DELETE_STARTED: 'SCALE_DELETE_STARTED',
  SCALE_FETCH_ERROR: 'SCALE_FETCH_ERROR',
  SCALE_FETCH_STARTED: 'SCALE_FETCH_STARTED',
  SET_NAME: 'SET_NAME',
  TRANSPOSE_SCALE: 'TRANSPOSE_SCALE',
};

export default scaleTypes;
