const actionTypes = {
  SET_DISPLAYED_CHORD: 'SET_DISPLAYED_CHORD',
  SET_DISPLAYED_NOTE: 'SET_DISPLAYED_NOTE',
  TOGGLE_IS_EDITING: 'TOGGLE_IS_EDITING',
  TOGGLE_SHOW_INTERVALS: 'TOGGLE_SHOW_INTERVALS',
};

export default actionTypes;
