const drumTypes = {
  FLUSH_DRUM_STATE: 'FLUSH_DRUM_STATE',
  SET_DISPLAYED_CHORD: 'SET_DISPLAYED_CHORD',
  SET_DISPLAYED_NOTE: 'SET_DISPLAYED_NOTE',
  SET_SHOW_INTERVALS: 'SET_SHOW_INTERVALS',
};

export default drumTypes;
