const actionTypes = {
  SET_BPM: 'SET_BPM',
  SET_SONG_METRE: 'SET_SONG_METRE',
  SET_SONG_SUBDIVISION: 'SET_SONG_SUBDIVISION',
  SET_CURRENT_BAR: 'SET_CURRENT_BAR',
  SET_CURRENT_BEAT: 'SET_CURRENT_BEAT',
  SET_IS_SONG_PLAYING: 'SET_IS_SONG_PLAYING',
  ADD_BAR_TO_SONG: 'ADD_BAR_TO_SONG',
  DELETE_BAR_FROM_SONG: 'DELETE_BAR_FROM_SONG',
  TOGGLE_EDIT_SONG: 'TOGGLE_EDIT_SONG',
  COPY_BAR_TO_NEXT: 'COPY_BAR_TO_NEXT',
  COPY_BAR_TO_END: 'COPY_BAR_TO_END',
};

export default actionTypes;
