const actionTypes = {
  SET_BPM: 'SET_BPM',
  SET_SONG_TIME: 'SET_SONG_TIME',
  SET_SONG_GRID: 'SET_SONG_GRID',
  SET_CURRENT_BAR: 'SET_CURRENT_BAR',
  SET_CURRENT_BEAT: 'SET_CURRENT_BEAT',
  SET_IS_SONG_PLAYING: 'SET_IS_SONG_PLAYING',
  ADD_BAR_TO_SONG: 'ADD_BAR_TO_SONG',
  DELETE_BAR_FROM_SONG: 'DELETE_BAR_FROM_SONG',
};

export default actionTypes;
