const actionTypes = {
  ADD_BAR_TO_SONG: 'ADD_BAR_TO_SONG',
  DELETE_BAR_FROM_SONG: 'DELETE_BAR_FROM_SONG',
  CHANGE_BAR_IN_PLACE: 'CHANGE_BAR_IN_PLACE',
  COPY_BAR_TO_END: 'COPY_BAR_TO_END',
  COPY_BAR_TO_NEXT: 'COPY_BAR_TO_NEXT',
  SET_BPM: 'SET_BPM',
  SET_SONG_DIFFICULTY: 'SET_SONG_DIFFICULTY',
  SET_SONG_METRE: 'SET_SONG_METRE',
  SET_SONG_SUBDIVISION: 'SET_SONG_SUBDIVISION',
  SET_SONG_TITLE: 'SET_SONG_TITLE',
};

export default actionTypes;
