const actionTypes = {
  ADD_NEW_BAR: 'ADD_NEW_BAR',
  DELETE_BAR: 'DELETE_BAR',
  DUPLICATE_BAR: 'DUPLICATE_BAR',
  // LOAD_SONG: 'LOAD_SONG',
  MOVE_BAR: 'MOVE_BAR',
  UPDATE_BAR_SUBDIVISION: 'UPDATE_BAR_SUBDIVISION',
  UPDATE_BEAT: 'UPDATE_BEAT',
  UPDATE_SONG: 'UPDATE_SONG',
  UPDATE_SONG_INFO: 'UPDATE_SONG_INFO',
};

export default actionTypes;
