const actionTypes = {
  SET_BPM: 'SET_BPM',
  SET_SONG_DIFFICULTY: 'SET_SONG_DIFFICULTY',
  SET_SONG_METRE: 'SET_SONG_METRE',
  SET_SONG_SUBDIVISION: 'SET_SONG_SUBDIVISION',
  SET_SONG_TITLE: 'SET_SONG_TITLE',
};

export default actionTypes;
