const actionTypes = {
  LOAD_SONG: 'LOAD_SONG',
  UPDATE_SONG_INFO: 'UPDATE_SONG_INFO',
  ADD_NEW_BAR: 'ADD_NEW_BAR',
  CLEAR_SONG: 'CLEAR_SONG',
  DELETE_BAR: 'DELETE_BAR',
  DUPLICATE_BAR: 'DUPLICATE_BAR',
  LOAD_BARS: 'LOAD_BARS',
  MOVE_BAR: 'MOVE_BAR',
  SET_BAR_METRE: 'SET_BAR_METRE',
  SET_BAR_SUBDIVISION: 'SET_BAR_SUBDIVISION',
  UPDATE_BEAT: 'UPDATE_BEAT',
  UPDATE_MEASURE_AND_BEATS: 'UPDATE_MEASURE_AND_BEATS',
};

export default actionTypes;
