const actionTypes = {
  ADD_NEW_BAR: 'ADD_NEW_BAR',
  CLEAR_SONG: 'CLEAR_SONG',
  DELETE_BAR: 'DELETE_BAR',
  DUPLICATE_BAR: 'DUPLICATE_BAR',
  SET_BAR_METRE: 'SET_BAR_METRE',
  SET_BAR_SUBDIVISION: 'SET_BAR_SUBDIVISION',
  UPDATE_BEAT: 'UPDATE_BEAT',
  UPDATE_MEASURE_AND_BEATS: 'UPDATE_MEASURE_AND_BEATS',
};

export default actionTypes;
