const actionTypes = {
  ADD_NEW_BAR: 'ADD_NEW_BAR',
  COPY_BAR_TO_END: 'COPY_BAR_TO_END',
  // COPY_BAR_TO_NEXT: 'COPY_BAR_TO_NEXT',
  DELETE_BAR: 'DELETE_BAR',
  SET_BAR_METRE: 'SET_BAR_METRE',
  SET_BAR_SUBDIVISION: 'SET_BAR_SUBDIVISION',
  UPDATE_BEAT: 'UPDATE_BEAT',
};

export default actionTypes;
