const actionTypes = {
  ADD_NEW_BAR: 'ADD_NEW_BAR',
  DELETE_BAR: 'DELETE_BAR',
  DUPLICATE_BAR: 'DUPLICATE_BAR',
  SET_BAR_METRE: 'SET_BAR_METRE',
  SET_BAR_SUBDIVISION: 'SET_BAR_SUBDIVISION',
  UPDATE_BEAT: 'UPDATE_BEAT',
};

export default actionTypes;
